### ISSUE TITLE
Deployer Cutting Recipes don't work in 1.2.0

### ISSUE THREAD

**Issue by FusionSwarly** [DragonsPlusMinecraft/CreateCentralKitchen#15]
### Minecraft Version

1.19.2

### Describe the Bug

Cutting board recipes don't work with deployers. I've tried several different cutting board recipes using deployers on mechanical belts and item depots and nothing works. 

I disabled all of my farmers delight addons and it still breaks, but when I reverted to version 1.1.0 it worked fine. This seems to be a bug introduced in version 1.2.0.

### Reproduction Steps

1. Set up a deployer over a running mechanical belt or item depot
2. Give the deployer a knife
3. Put any item that can be used in the chopping board under the deployer

### Expected Result

The deployer should chop the items below it with the knife according to the cutting recipe, but it does nothing. If on a mechanical belt, the item should stop and the deployer should cut it, but instead it just passes by.

### Other Mods

AdvancementPlaques-1.19.2-1.4.7
AI-Improvements-1.19.2-0.5.2
aileron-1.19-forge-1.0.0
alexsdelight-1.4.1
alexsmobs-1.21.1
appleskin-forge-mc1.19-2.4.2
architectury-6.4.62-forge
AttributeFix-Forge-1.19.2-17.1.3
BoatBreakFix-Universal-1.0.11
brvsb-1.0.2-mc1.19.2
bwncr-forge-1.19.2-3.14.1
cakechomps-forge-6.0.0+1.19.2
catalogue-1.7.0-1.19.2
citadel-2.1.1-1.19
cloth-config-8.2.88-forge
Clumps-forge-1.19.2-9.0.0+14
collectorsreap-1.19-1.1.2
configured-2.0.1-1.19.2
Controlling-forge-1.19.2-10.0+7
create_central_kitchen-1.19.2-for-create-0.5.0.i-1.1.0
create-1.19.2-0.5.0.i
Ding-1.19.2-Forge-1.4.0
entityculling-forge-1.5.2-mc1.19.1
FarmersDelight-1.19-1.2.0
FarmersRespite-1.19-2.0
farsight-1.19.2-2.1
ferritecore-5.0.3-forge
findme-3.1.0-forge
flywheel-forge-1.19.2-0.6.8.a
geophilic-forge-1.19-1.0.1
global_packs-forge-1.19.2-1.14.2_forge
Highlighter-1.19.1-1.1.4
Iceberg-1.19.2-forge-1.1.4
InsaneLib-1.7.5-mc1.19.2
jei-1.19.2-forge-11.5.2.1007
koremods-modlauncher-0.5.0
kotlinforforge-3.9.1-all
LegendaryTooltips-1.19.2-forge-1.4.0
modelfix-1.8
moonlight-1.19.2-2.2.2-forge
NekosEnchantedBooks-1.19-1.8.0
NethersDelight-1.19-3.0
NoChatReports-FORGE-1.19.2-v1.5.1
notenoughanimations-forge-1.6.2-mc1.19.2
Nullscape_v1.2a
oculus-flywheel-compat-1.19.2-0.1.6-ALPHA
oculus-mc1.19.2-1.2.8a
pluto-mc1.19.2-0.0.7
Prism-1.19.1-1.0.2
rubidium_extras-1.19.2_v1.3.2
rubidium-0.6.2
saturn-mc1.19.2-0.0.1
screenshot-to-clipboard-1.0.9-forge
smarterfarmers-1.19.2-1.7.0
snowundertrees-1.19.2-1.3.1
starlight-1.1.1+forge.cf5b10b
Villager Comfort-1.19.2-1.0.0
voicechat-forge-1.19.2-2.3.28
worldedit-mod-7.2.12
yeetusexperimentus-1.0.1-build.2+mc1.19.1

### Mod Version

1.2.0

### Forge Version

43.2.0

**Comment by RaymondBlaze** [comment]
Confirmed, has been fixed in https://github.com/DragonsPlusMinecraft/CreateCentralKitchen/commit/2e850c7e01d0430e575805f3e0fcf51d3f8ecda0 and will be released in the upcoming 1.2.1.
