### ISSUE TITLE
Blaze stove export

### ISSUE THREAD

**Issue by albertosaurio65** [DragonsPlusMinecraft/CreateCentralKitchen#18]
### Describe the your request

![image](https://user-images.githubusercontent.com/70109413/220649915-d28b7dc2-f414-4648-88df-596af6718c9c.png)

use a arm to export cooked food, it only allows you to select the blaze stove with the arm to import, not to export the finished foods

**Comment by MarbleGateKeeper** [comment]
Cooked food will be popped out automatically. It follows the behavior of stove of Farmer's Delight.
