### ISSUE TITLE
Recipe for Cakes

### ISSUE THREAD

**Issue by albertosaurio65** [DragonsPlusMinecraft/CreateCentralKitchen#19]
### Describe the your request

Some recipes cant be made with the mixer, like cakes: 
![image](https://user-images.githubusercontent.com/70109413/221365244-c0d2b7c0-ed7e-41a7-aae9-ef603731ee12.png)
![image](https://user-images.githubusercontent.com/70109413/221365288-13bfac62-4e5a-412a-ae8a-c1d9fe68de4e.png)

It will be more realistic if you mix it, no with a craft forme

**Comment by RaymondBlaze** [comment]
A general recipe style for cakes is yet to be decided.
We shall figure it out when 1.3.0 is out with Neapolitan support.
Simple Mixing Recipes could be a choice, but I do feel like finding some neater solutions.
Feel free to discuss under this issue before we reach a conclusion :)

**Comment by Junnaturefox** [comment]
Add tag:cake for cakes and then add a new machine/cooking guide for making cakes?
Maybe a Cake Printer?

**Comment by RaymondBlaze** [comment]
> Add tag:cake for cakes and then add a new machine/cooking guide for making cakes? Maybe a Cake Printer?

Nah, this idea has gone a bit far in complexity for us and the players.
Sequenced Assembly should be the most complex solution that is acceptable.

**Comment by RaymondBlaze** [comment]
Closed in https://github.com/DragonsPlusMinecraft/CreateCentralKitchen/commit/1afdec2bfeddfe0eb136c8aece09d0a5d3b41e62, using Compacting Recipes as the final solution.
