### ISSUE TITLE
Pondering baskets crashes the game

### ISSUE THREAD

**Issue by WaterOre** [DragonsPlusMinecraft/CreateCentralKitchen#24]
### Minecraft Version

1.19.2

### Describe the Bug

Loading the ponder sequence for the basket crashes the game. The sequence is able to initialize and gets as far as displaying two baskets and a chute, but when attempting to insert further items or blocks the game will crash. 

### Reproduction Steps

1. Launch the game with Farmer's Delight, Create, and Create: Central Kitchen
2. Attempt to ponder baskets from the inventory

### Expected Result

Ponder was expected to load and play, does not.

### Crash Report or Log

[crash-2023-03-25_19.26.30-client.txt](https://github.com/DragonsPlusMinecraft/CreateCentralKitchen/files/11070482/crash-2023-03-25_19.26.30-client.txt)

### Other Mods

This instance is available on Curseforge

dynamiclightsreforged-1.19.2_v1.4.0.jar
		YungsBetterDungeons-1.19.2-Forge-3.2.2.jar
		supermartijn642configlib-1.1.6b-forge-mc1.19.jar
		infernal-expansion-1.19.2-2.5.3.jar
		WorldDataLoader-1.19-1.0.jar
		Entity_Collision_FPS_Fix-forge-1.19-2.0.0.0.jar
		rubidium-0.6.2a.jar
		modernfix-mc1.19.2-3.2.1.jar
		namepain-1.4.1 forge-1.19.x.jar
		YungsApi-1.19.2-Forge-3.8.9.jar
		guardvillagers-1.19.2-1.5.5.jar
		balm-forge-1.19.2-4.5.7.jar
		SnowRealMagic-1.19.2-forge-6.5.0.jar
		gunswithoutroses-1.19-1.1.1.jar
		JustEnoughResources-1.19.2-1.2.2.200.jar
		chat_heads-0.10.7-forge-1.19.2.jar
		YungsBetterNetherFortresses-1.19.2-Forge-1.0.5.jar
		cloth-config-8.2.88-forge.jar
		supplementaries-1.19.2-2.2.63.jar
		durabilitytooltip-1.1.4-forge-mc1.19.jar
		TaxOceanVillager+M.1.19+ForM-1.1.2.jar
		do-a-barrel-roll-2.6.2+1.19.2-forge.jar
		eyes_mod_forge_1.19.2_0.1.jar
		sleep_tight-1.19.2-1.0.12.jar
		DarkerDepths-1.19.2-1.0.0.jar
		Highlighter-1.19.1-1.1.4.jar
		curios-forge-1.19.2-5.1.3.0.jar
		YungsExtras-1.19.2-Forge-3.1.0.jar
		swashbucklers2.4 1.19.jar
		overweightfarming-1.19.2-2.0.1-forge.jar
		soulfired-1.19.2-3.1.0.0-final-forge.jar
		Chimes-1.1.4-1.19.jar
		the_bumblezone_forge-6.6.18+1.19.2.jar
		windswept-1.19.2-2.2.1.jar
		FastLeafDecay-30.jar
		YungsBetterMineshafts-1.19.2-Forge-3.2.0.jar
		BorderlessWindow-1.19.1-1.5.2.jar
		QuarkOddities-1.18.jar
		Kiwi-1.19.1-forge-8.3.4.jar
		createbigcannons-1.19.2-beta-0.5.b.jar
		jei-1.19.2-forge-11.6.0.1013.jar
		Paxi-1.19.2-Forge-3.0.1.jar
		immersive_weathering-1.19.2-1.2.8-forge.jar
		shutupexperimentalsettings-1.0.5.jar
		SereneSeasons-1.19.2-8.1.0.24.jar
		sereneseasonfix-1.19.2-1.0.7.jar
		trolldom-1.19.2-1.1.0.jar
		JeiTweaker-forge-1.19.2-4.0.11.jar
		CraftTweaker-forge-1.19.2-10.1.39.jar
		forge-1.19.2-43.2.0-universal.jar
		Zombie Friends 1.18-1.19-1.0.3.jar
		voicechat-forge-1.19.2-2.3.28.jar
		TerraBlender-forge-1.19.2-2.0.1.128.jar
		le_fishe_au_chocolat-1.19.2-1.0.jar
		MouseTweaks-forge-mc1.19-2.23.jar
		NoChatReports-FORGE-1.19.2-v1.5.1.jar
		EmendatusEnigmatica-2.1.4-build.58+mc1.19.2.jar
		spectrelib-forge-0.11.0+1.19.jar
		Ding-1.19.2-Forge-1.4.0.jar
		CreateTweaker-1.19.2-3.0.0.5.jar
		kffmod-3.11.0.jar
		notenoughanimations-forge-1.6.2-mc1.19.2.jar
		flywheel-forge-1.19.2-0.6.8.a.jar
		FarmersRespite-1.19-2.0.jar
		ecologics-forge-1.19.2-2.1.11.jar
		betterfog-1.19.2-1.1.1.jar
		gravestone-1.19.2-1.0.1.jar
		polymorph-forge-0.46.1+1.19.2.jar
		JustEnoughProfessions-forge-1.19.2-2.0.2.jar
		AutoRegLib-1.8.2-55.jar
		entityculling-forge-1.6.1-mc1.19.2.jar
		DoubleSlabs-1.19-6.1.0.jar
		canary-mc1.19.2-0.1.9.jar
		DamageTilt-1.19-forge-0.1.2.jar
		PuzzlesLib-v4.3.12-1.19.2-Forge.jar
		goated-1.19.2-1.2.1.jar
		End's Phantasm - BETAv1.2.10.5 - 1.19.2.jar
		CyclopsCore-1.19.2-1.18.2.jar
		YungsBetterWitchHuts-1.19.2-Forge-2.1.0.jar
		v_slab_compat-1.19.2-1.4.jar
		netherportalfix-forge-1.19-10.0.1.jar
		DistinguishedPotions-v4.0.1-1.19.2-Forge.jar
		naturalist-forge-2.1.1-1.19.2.jar
		incontrol-1.19-7.1.3.jar
		YungsBetterOceanMonuments-1.19.2-Forge-2.1.0.jar
		Tips-Forge-1.19.2-8.0.27.jar
		immersive_aircraft-0.3.1+1.19.2-forge.jar
		darkness-forge-mc119-2.0.101.jar
		Controlling-forge-1.19.2-10.0+7.jar
		Prism-1.19.1-1.0.2.jar
		Placebo-1.19.2-7.1.7.jar
		citadel-2.1.1-1.19.jar
		alexsmobs-1.21.1.jar
		cloudstorage-1.3.4-1.19.2.jar
		mixinextras-forge-0.2.0-beta.5.jar
		Bookshelf-Forge-1.19.2-16.2.18.jar
		create_dragon_lib-1.19.2-1.1.2.jar
		jeed-1.19.2-1.18.jar
		FpsReducer2-forge-1.19.2-2.1.jar
		hauntedharvest-1.19.2-3.1.4.jar
		twilightforest-1.19.2-4.2.1518-universal.jar
		FarmersDelight-1.19-1.2.0.jar
		culturaldelights-1.19.2-0.15.1.jar
		endsdelight-1.19.2-1.0.jar
		Reblured-1.19.1-1.2.0.jar
		collectorsreap-1.19-1.2.jar
		suppsquared-1.19.2-1.0.8.jar
		collective-1.19.2-6.53.jar
		spyglass_improvements-1.4+mc1.19+forge.jar
		BetterThirdPerson-Forge-1.19-1.9.0.jar
		YungsBetterStrongholds-1.19.2-Forge-3.2.0.jar
		architectury-6.5.69-forge.jar
		SimpleDiscordRichPresence-forge-3.0.4-build.27+mc1.jar
		sullysmod-2.3.1-beta.jar
		geckolib-forge-1.19-3.1.40.jar
		polylib-forge-1900.0.2-build.42.jar
		UniversalClockHUD-FORGE-1.19.2-v1.6.0.jar
		BetterAdvancements-1.19.2-0.2.2.142.jar
		rhino-forge-1902.2.2-build.264.jar
		kubejs-forge-1902.6.0-build.142.jar
		redstonepen-1.19.2-forge-1.2.20.jar
		gunswithoutrosesadditions-1.19.2-1.0.1.jar
		EasyMagic-v4.3.3-1.19.2-Forge.jar
		Map Atlases-forge-1.19.2-3.0.1.jar
		paletteblocks-0.2.0-1.19.2.jar
		create-1.19.2-0.5.0.i.jar
		Delightful-1.19.2-3.2.2.jar
		create_central_kitchen-1.19.2-for-create-0.5.0.i-1.jar
		Steam_Rails-1.19.2-1.1.1.jar
		liquidburner-1.19.2-0.3a.jar
		waystones-forge-1.19.2-11.3.1.jar
		custom_stars-1.19.2-1.2.jar
		breezy-1.19.2-1.0.4.jar
		configured-2.0.1-1.19.2.jar
		CustomPlayerModels-1.19-0.6.6a.jar
		Decorative Blocks-forge-1.19.2-3.0.0.jar
		BadMobs-1.19.2-16.1.3.jar
		ftbbackups2-forge-1.19.2-1.0.18.jar
		everycomp-1.19.2-2.2.3.jar
		YungsBetterDesertTemples-1.19.2-Forge-2.2.2.jar
		farsight-1.19.2-2.1.jar
		Continents_1.19.3_v1.1.2.jar
		Block Swap-forge-1.19-2.0.0.0.jar
		blueprint-1.19.2-6.1.2.jar
		boatload-1.19.2-4.2.1.jar
		environmental-1.19.2-3.0.0.jar
		savage_and_ravage-1.19.2-5.0.4.jar
		clayworks-1.19.2-2.0.1.jar
		upgrade_aquatic-1.19.2-5.0.0.jar
		neapolitan-1.19.2-4.0.2.jar
		respiteful-1.19.2-1.1.0.jar
		personality-1.19-3.0.1.jar
		autumnity-1.19.2-4.0.0.jar
		allurement-1.19.2-3.1.0.jar
		woodworks-1.19.2-2.2.1.jar
		incubation-1.19-3.0.0.jar
		buzzier_bees-1.19-5.0.1.jar
		berry_good-1.19.2-6.0.1.jar
		3dskinlayers-forge-1.5.2-mc1.19.1.jar
		seasonals-1.19.2-4.0.0.jar
		wearablebackpacks-1.19.2-0.1.2.jar
		ColossalChests-1.19.2-1.8.4.jar
		craftingtweaks-forge-1.19-15.1.6.jar
		weakerspiderwebs-1.19.2-3.2.jar
		EnchantmentDescriptions-Forge-1.19.2-13.0.14.jar
		moonlight-1.19.2-2.2.26-forge.jar
		advancementframes-1.19.2-2.0.0.jar
		labels-1.19.2-1.8.jar
		spelunkery-1.19.2-0.1.13-forge.jar
		mysticaloaktree-1.19.2-1.8.jar
		smarterfarmers-1.19.2-1.7.1.jar
		moyai-1.19.2-2.0.1.jar
		gardens-of-the-dead-forge-2.0.1.jar
		snowyspirit-1.19.2-2.1.6.jar
		another_furniture-forge-2.1.2-1.19.2.jar
		spidersproducewebs-1.19.2-3.1.jar
		Oreganized 1.19.2-2.0.2.jar
		NethersDelight-1.19-3.0.jar
		atmospheric-1.19.2-5.0.0.jar
		peculiars-4.0.0.jar
		Iceberg-1.19.2-forge-1.1.4.jar
		reliquary-1.19.2-2.0.20.1166.jar
		Quark-3.4-394.jar
		vanillapluscompat-1.6.1-1.19.2.jar
		mutil-1.19.2-5.1.0.jar
		LegendaryTooltips-1.19.2-forge-1.4.0.jar
		FastWorkbench-1.19.2-7.0.1.jar
		abnormals_delight-1.19.2-4.0.2.jar
		DiagonalFences-v4.2.3-1.19.2-Forge.jar
		alexsdelight-1.4.1.jar
		fastfooddelight-1.19-1.2.3.jar
		moredragoneggs-3.2.jar
		BetterF3-4.0.0-Forge-1.19.2.jar
		cave-enhancements-1.19.2-2.1.11-forge.jar
		heartstone-1.19.2-1.1.1.jar
		create_enchantment_industry-1.19.2-for-create-0.5.jar
		cpm-svc-compat-1.1.0.jar

### Mod Version

create_central_kitchen-1.19.2-for-create-0.5.0.i-1.2.2

### Forge Version

Forge - 43.2.0

**Comment by MarbleGateKeeper** [comment]
problem caused by Canary.
```
java.lang.ClassCastException: class com.simibubi.create.foundation.ponder.PonderWorld cannot be cast to class net.minecraft.world.level.chunk.ChunkAccess (com.simibubi.create.foundation.ponder.PonderWorld is in module create@0.5.0.i of loader 'TRANSFORMER' @9729a97; net.minecraft.world.level.chunk.ChunkAccess is in module minecraft@1.19.2 of loader 'TRANSFORMER' @9729a97)
	at com.abdelaziz.canary.common.entity.CanaryEntityCollisions.getCollisionShapeBelowEntity(CanaryEntityCollisions.java:195) ~[canary-mc1.19.2-0.1.9.jar%23363!/:0.1.9] {re:mixin,re:classloading}
```
Canary was trying to cast PonderWorld to incompatible world class.

**Comment by MarbleGateKeeper** [comment]
Also here is the issue of same problem: https://github.com/AbdElAziz333/Canary/issues/112
