### ISSUE TITLE
Crash loading new world due to missing recipe loading condition

### ISSUE THREAD

**Issue by katubug** [DragonsPlusMinecraft/CreateCentralKitchen#31]
### Minecraft Version

1.19.2

### Describe the Bug

When attempting to load an existing world, I got a notice about datapack issues and was prompted to go into safe mode or try again. When I attempted to make a new world, the game crashed to desktop. This does not occur in version ~~1.3.0~~1.2.2

### Reproduction Steps

1. Using the Cottage Witch modpack version 1.13a (not yet released, working on it), update to the most recent CCK.
2. Launch game and try to access existing world or create new one.

### Expected Result

I expected the existing world to load, and a new world to be created.

### Crash Report or Log

https://pastebin.com/gkYLFgXS

### Other Mods

Listed in crash report.

### Mod Version

~~1.3.1~~1.3.0

### Forge Version

43.2.6

**Comment by RaymondBlaze** [comment]
Integration recipes for Collector's Reap are referencing Neapolitan related fluids, causing the problem.
This has been fixed in 1.3.1 using proper `ModLoadingCondition`.
