### ISSUE TITLE
Crash on newest version

### ISSUE THREAD

**Issue by ZEROX7** [DragonsPlusMinecraft/CreateCentralKitchen#39]
### Minecraft Version

1.19.2

### Describe the Bug

crash on startup

### Reproduction Steps

1.
2.
3.
...

### Expected Result

visible main menu

### Crash Report or Log

https://gist.github.com/ZEROX7/b0e462014be3bc9cd60cda9de2b91c29

### Mod Version

1.3.3

### Forge Version

43.2.8

**Comment by brisingraerowing** [comment]
The current CCK version is incompatible with Brewin' and Chewin'. I've reported this there.
