### ISSUE TITLE
java.lang.Exception: Mod Loading has failed

### ISSUE THREAD

**Issue by ClaudiusMinimus** [DragonsPlusMinecraft/CreateCentralKitchen#40]
### Minecraft Version

1.19.2

### Describe the Bug

Was trying to add your mod to my pack [Create on a Potato PC: Ultunate](https://legacy.curseforge.com/minecraft/modpacks/create-on-a-potato) and the pack crashed on startup.

### Reproduction Steps

1. Install create_central_kitchen-1.19.2-for-create-0.5.0.i-1 with the rest of my pack
2. Start pack
3. Boom! Crash. 
...

### Expected Result

Should run without crashing on startup.

### Screenshots and Videos

[crash-2023-05-03_10.35.51-fml.txt](https://github.com/DragonsPlusMinecraft/CreateCentralKitchen/files/11384968/crash-2023-05-03_10.35.51-fml.txt)

### Other Mods

See crash report starting line 172

### Mod Version

create_central_kitchen-1.19.2-for-create-0.5.0.i-1

### Forge Version

43.2.8

**Comment by RaymondBlaze** [comment]
I can't reproduce this crash in a brand new Minecraft instance and existing instance works fine too.
I wonder if you have tried cleanup your `config` folder, I need more detailed information to validate this issue.

**Comment by ClaudiusMinimus** [comment]
Thank you for testing! I just did a fresh install of the pack from Curseforge and the loaded fine and was able to generate a new world with no errors. Since the crash happened while updating the pack, I will look for a conflicting updated mod and try clearing out the configs. I'll let you know if I find the culprit.
Thanks again,
CM
