### ISSUE TITLE
Not compatible with Miners Delight 1.1 Update

### ISSUE THREAD

**Issue by Nanamiya738** [DragonsPlusMinecraft/CreateCentralKitchen#42]
### Minecraft Version

1.18.2

### Describe the Bug

when I use JEI or just put recipe by hand. the game crash 
and this is what crash report says
"Description: mouseReleased event handler"

Create+ modpack (4.11.1), prism launcher

### Reproduction Steps

1.
2.
3.
...

### Expected Result

I want to use the mod normally without crash

### Mod Version

1.3.1

### Forge Version

40.2.0

**Comment by MarbleGateKeeper** [comment]
Crash-log is needed.

**Comment by Nanamiya738** [comment]
crash report↓
https://github.com/Nanamiya738/mcpack/blob/main/crash%20report

**Comment by Nanamiya738** [comment]
the log about it ↓
https://mclo.gs/vcXECz0

**Comment by MarbleGateKeeper** [comment]
Here's the thing:
Miners Delight removed `CupConversionHandler` in [this commit](https://github.com/SammySemicolon/MinersDelight/commit/ac5f7741a89259eb07a2716cc9a1468e4dbddcd9#diff-772c7eb7ebb089c25b03df5c2e8f27b4da7c930df07f0f8d2d08de23bd8d7970L2)
Please wait for a fix.

**Comment by SiverDX** [comment]
@MarbleGateKeeper 
The 1.19.2 version already has the code for 1.1.1 version of that mod

https://github.com/DragonsPlusMinecraft/CreateCentralKitchen/blob/1.19.2/0.5.0-dev/src/main/java/plus/dragons/createcentralkitchen/content/logistics/item/guide/minersCooking/MinersCookingGuide.java

Could use that

**Comment by Nanamiya738** [comment]
so it's ok to use the newest 1.3.3 ? thanks for the update

**Comment by MarbleGateKeeper** [comment]
> so it's ok to use the newest 1.3.3 ? thanks for the update

Yep. Safe to use.
