### ISSUE TITLE
Texture Breaks when flowing next to things like grass

### ISSUE THREAD

**Issue by zachsai** [DragonsPlusMinecraft/CreateCentralKitchen#43]
### Minecraft Version

1.19.2

### Describe the Bug

![image](https://github.com/DragonsPlusMinecraft/CreateCentralKitchen/assets/63996164/20d8bb0b-78bb-414d-9931-a66310fc1f37)

### Reproduction Steps

flow next to grass, tomato, sap, syrup 

### Expected Result

proper texture

### Screenshots and Videos

![image](https://github.com/DragonsPlusMinecraft/CreateCentralKitchen/assets/63996164/85a5ef8b-5cc8-4af3-8607-66bc19d95465)

### Mod Version

1.3.5

### Forge Version

43.2.10

**Comment by MarbleGateKeeper** [comment]
Can't reproduce in any branch. Caused by other mod.

![](https://github.com/DragonsPlusMinecraft/CreateCentralKitchen/assets/19358421/9698793f-2c13-49ba-ab4c-426439f91686)
