### ISSUE TITLE
MC Launcher crashes upon Play

### ISSUE THREAD

**Issue by itsdeadfrosty** [DragonsPlusMinecraft/CreateCentralKitchen#44]
### Minecraft Version

1.18.2

### Describe the Bug

i wish i had a crashlog for you, i do however, have a manifest for you at the very least, so you can.Compare for the future if anybody else mentions that this crashes their game, maybe some mods will line up to tell whats wrong, but yeah it wont even boot up past the launcher. 

Your mod looks super cool and I'm really kind of disappointed it doesn't run. For me. However, here's hoping that something changes in the future and it does work. That would be awesome.

I hope this helps to some degree.

### Reproduction Steps

1. Install mod.
2. Open Minecraft Launcher.
3. Press play.
4. Profit- i mean crash.

### Expected Result

shit runs lol

### Screenshots and Videos

![Screenshot (1)](https://github.com/DragonsPlusMinecraft/CreateCentralKitchen/assets/132015237/43f5dc87-59b5-4935-b1b2-65d75b5e27a9)
[manifest.txt](https://github.com/DragonsPlusMinecraft/CreateCentralKitchen/files/11469533/manifest.txt)

### Other Mods

[manifest.txt](https://github.com/DragonsPlusMinecraft/CreateCentralKitchen/files/11469533/manifest.txt)

### Mod Version

More Babies-forge-1.18.2-1.0.0

**Comment by CJL48** [comment]
As it happens, I do have a crash log for what may well be the same issue.
MultiMC
Minecraft 1.18.2
Forge 40.2.0
LWJGL 3.2.2

create-1.18.2-0.5.0.i
create-confectionery1.18.2_v1.0.8
create_central_kitchen-1.18.2-for-create-0.5.0.i-1.3.2
create_enchantment_industry-1.18.2-for-create-0.5.0.i-1.2.0
createaddition-1.18.2-20230426a
flywheel-forge-1.18.2-0.6.8.a
Farmer's Delight 1.18.2-1.2.0

I had more mods installed, but pared it down to make troubleshooting a bit easier.

[crash-2023-05-18_14.10.17-fml.txt](https://github.com/DragonsPlusMinecraft/CreateCentralKitchen/files/11510485/crash-2023-05-18_14.10.17-fml.txt)

Another crash log, this one with only Create, Flywheel, and Central Kitchen installed:

[crash-2023-05-18_14.12.36-fml.txt](https://github.com/DragonsPlusMinecraft/CreateCentralKitchen/files/11510496/crash-2023-05-18_14.12.36-fml.txt)

I hope that this is helpful to you.

**Comment by SiverDX** [comment]
Would have to provide your `common` config file of the mod since there seems to be a problem with it

**Also**:
If Minecraft crashes like that you can usually still provide the `debug.log` file
(Location depends on the launcher it seems - if you ultimately start it from the vanilla launcher (which gets opened by the Curse launcher e. g.) you can also go into the settings and set it so that the console (log) window gets opened and provide that)

**Comment by CJL48** [comment]
Sorry about the delay. Having the mod generate a fresh config file actually seems to have fixed the issue.
The old config file:
[create_central_kitchen-common.toml.txt](https://github.com/DragonsPlusMinecraft/CreateCentralKitchen/files/11690768/create_central_kitchen-common.toml.txt)
Debug Log:
[debug.log](https://github.com/DragonsPlusMinecraft/CreateCentralKitchen/files/11690777/debug.log)

Installation Information:
Minecraft 1.18.2
Forge 40.2.4
LWJGL 3.2.2
AutoRegLib-1.7-53.jar
FarmersDelight-1.18.2-1.2.0.jar
FramedBlocks-5.11.4.jar
ImmersiveEngineering-1.18.2-8.4.0-161.jar
Mekanism-1.18.2-10.2.5.465.jar
MekanismAdditions-1.18.2-10.2.5.465.jar
MekanismGenerators-1.18.2-10.2.5.465.jar
Patchouli-1.18.2-71.1.jar
Quark-3.2-358.jar
QuarkOddities-1.18.jar
StorageDrawers-1.18.2-10.2.1.jar
SuperCircuitMaker2-0.2.9+1.18.2.jar
TKLib-0.0.23+1.18.2.jar
antiqueatlas-7.1.1-forge-mc1.18.2.jar
architectury-4.11.93-forge.jar
cloth-config-6.3.81-forge.jar
create-1.18.2-0.5.1.b.jar
create-confectionery1.18.2_v1.0.9.jar
create_central_kitchen-1.18.2-for-create-0.5.1.b-1.3.7.jar
create_enchantment_industry-1.18.2-for-create-0.5.1.b-1.2.4.b.jar
createaddition-1.18.2-20230527a.jar
flywheel-forge-1.18.2-0.6.8.a.jar
hexerei-0.2.2.jar
jei-1.18.2-forge-10.2.1.1004.jar
mutil-1.18.2-4.5.0.jar
pneumaticcraft-repressurized-1.18.2-3.6.0-19.jar
tetra-1.18.2-4.10.1.jar

**Comment by SiverDX** [comment]
I'm not sure why, how or when it is happening but this error seems to be caused by this entry in the common config file not having a `#` in front of it (indicating that it is a comment): `[@cui:RequiresReload:both]`

If you add a `#` before that line it should work without having to delete the config

**Comment by MarbleGateKeeper** [comment]
A nightconfig problem I think. RaymondBlaze says he has a workaround but he's busy now.

**Comment by VirtualGaming1** [comment]
Just want add on that I just had this issue on my server. I has been working well but I had the same issue. weird thing is this happen also while the server was running fully and my server stop working without anything showing in the console. This happen just randomly
