### ISSUE TITLE
Create 0.5.1 compat when?

### ISSUE THREAD

**Issue by Grigew** [DragonsPlusMinecraft/CreateCentralKitchen#46]
### Minecraft Version

1.19.2

### What Mods Conflicts with

Create 0.5.1

### Describe the Incompatibility

?

### Other Mods

?

### Additional Context

?

### Crash Report or Log

?

### Mod Version

latest

### Incompatible Mod Version

0.5.1

**Comment by MarbleGateKeeper** [comment]
Please follow #48
