### ISSUE TITLE
Current version incompatible with Create 5.1 update

### ISSUE THREAD

**Issue by Branjoman** [DragonsPlusMinecraft/CreateCentralKitchen#47]
### Minecraft Version

1.19.2

### What Mods Conflicts with

Create 0.5.1b

### Describe the Incompatibility

Minecraft crashes on startup when trying to load Create: Central Kitchen with the latest Create update.

### Other Mods

N/A

### Additional Context

This incompatibility report is following on from #46

### Crash Report or Log

https://pastebin.com/0gQy3duw

### Mod Version

1.3.5

### Incompatible Mod Version

0.5.1b

### Forge Version

43.2.11

**Comment by MarbleGateKeeper** [comment]
Please follow #48
