### ISSUE TITLE
Refueling Blaze Stove with Lava Buckets using a Mechanical Arm does not return bucket

### ISSUE THREAD

**Issue by deskydesqui** [DragonsPlusMinecraft/CreateCentralKitchen#5]
### Minecraft Version

1.18.2

### Describe the Bug

Title. Bucket is returned when refueled by deployer or player. 

### Reproduction Steps

1. Set Mechanical Arm to refuel Blaze Stove with lava buckets
2. Allow Mechanical Arm to refuel stove

### Expected Result

Much like normal blaze burner behavior, an empty bucket should be returned after refueling the stove

### Other Mods

![Screenshot 2023-02-06 130403](https://user-images.githubusercontent.com/96780679/216887967-63e1e8aa-22f3-4158-8882-7c85010c879d.png)

### Mod Version

1.0.2

### Forge Version

40.2.1

**Comment by MarbleGateKeeper** [comment]
Fixed in 90c35d1334fb03ef3f37ebdace55becdf23e47f8
