### ISSUE TITLE
Cooking Guide Ponder Bug

### ISSUE THREAD

**Issue by MikeTheBuddy** [DragonsPlusMinecraft/CreateCentralKitchen#53]
### Minecraft Version

1.19.2

### Describe the Bug

When using the cooking guide, the ponder system seems unable to call upon the text associated with it, referring to the names of the text files instead of the text associated within them.

This creates the effect where Text

### Reproduction Steps

1.Open up a world
2.Ponder the Cooking Guide
3.See Results

### Expected Result

The cooking guide ponder is explained in detail how it works normally

### Screenshots and Videos

![image](https://github.com/DragonsPlusMinecraft/CreateCentralKitchen/assets/77366491/7bb86112-d24a-400c-87b2-74ae41c66a07)

### Mod Version

0.5.1b

**Comment by Irritated-Badger** [comment]
The same bug also effects the Miner's Guide
