### ISSUE TITLE
Dough and Wheat Dough

### ISSUE THREAD

**Issue by Jaitnium** [DragonsPlusMinecraft/CreateCentralKitchen#55]
### Minecraft Version

1.19.2

### What Mods Conflicts with

Create

### Describe the Incompatibility

This mod overwrites Create's Dough recipe, making it uncraftable. Only Wheat Dough can be created. Create's Dough can still be crafted using the Fan Washing method.

### Other Mods

Farmer's Delight

### Additional Context

Can't create Dough using 1 Wheat Flour and 1 Water Bucket with Central Kitchen installed

### Mod Version

1.19.2

**Comment by MarbleGateKeeper** [comment]
Thanks for reporting.

I'm currently in another city for my brother's graduation ceremony, and there will be no updates or fixes until the 28th. Sorry for inconvenience.
