### ISSUE TITLE
End's Delight Chorus Fruit Pie recipe is kinda bugged

### ISSUE THREAD

**Issue by curryducker** [DragonsPlusMinecraft/CreateCentralKitchen#60]
### Minecraft Version

1.19.2

### Describe the Bug

The Chorus Fruit Pie recipe is very big so it doesn't fit in JEI and the steps don't count past 6, i assume the recipe is generated (really love that btw) so maybe you can override it to a better recipe

### Reproduction Steps

Install JEI, End's Delight and Central Kitchen and check the recipe

### Expected Result

Uuuh i expected it to fit in frame i guess

### Screenshots and Videos

![image](https://github.com/DragonsPlusMinecraft/CreateCentralKitchen/assets/66020230/e86e9146-c2c9-42a6-8c46-95738f7510a9)

### Mod Version

1.3.9.c

### Forge Version

43.2.8

**Comment by MarbleGateKeeper** [comment]
Well. It is expected behavior.
The recipe works fine. It's Create JEI plugin Problem.
