### ISSUE TITLE
crash in Create 1.19.2 new version "F"

### ISSUE THREAD

**Issue by GitJhopa** [DragonsPlusMinecraft/CreateCentralKitchen#63]
### Minecraft Version

1.19.2

### Describe the Bug

[crash-2023-11-02_18.56.34-client.txt](https://github.com/DragonsPlusMinecraft/CreateCentralKitchen/files/13242003/crash-2023-11-02_18.56.34-client.txt)

### Reproduction Steps

update Create mod

### Expected Result

Crash.

### Mod Version

create_central_kitchen-1.19.2-for-create-0.5.1.e-1.3.9.d

### Forge Version

1.19.2-43.2.21

**Comment by MarbleGateKeeper** [comment]
1.18.2 incompat has been fixed. 1.19.2 will be fixed soon.
