### ISSUE TITLE
Bread's hunger value is double counted

### ISSUE THREAD

**Issue by WanweiInMod** [DragonsPlusMinecraft/CreateCentralKitchen#67]
### Minecraft Version

1.19.2

### Describe the Bug

When adding IguanaTweaksReborn with this mod, the bread's hunger value tweaked by IguanaTweaksReborn is double counted.

### Reproduction Steps

1.Config set "iguanatweaksreborn -> common.toml -> ["Hunger & Health"."Food & Drinks"] -> "Food Hunger Multiplier" = 0.5 "
2.Launching the game, found the hunger value of item "minecraft:bread" is "1" instead of "3"

### Expected Result

The hunger value of item "minecraft:bread" should be "3" instead of "1".

### Screenshots and Videos

![image](https://github.com/DragonsPlusMinecraft/CreateCentralKitchen/assets/93438604/24112c44-997b-49ab-bdaf-450073386a70)

### Other Mods

Iguana tweaks reborn 2.13.6-mc 1.19.2

### Mod Version

1.3.9e

### Forge Version

43.2.23

**Comment by Jelly-Candy** [comment]
我的意见是他这个mod的issue已经好几个月没人更新和维护了，你等他修还不如去找个人接盘

**Comment by MarbleGateKeeper** [comment]
We didn't modify this in any way.
