### ISSUE TITLE
Crash on world loading when world contains powered mixer above non-empty basin [1.20.1]

### ISSUE THREAD

**Issue by VoidLeech** [DragonsPlusMinecraft/CreateCentralKitchen#68]
### Minecraft Version

1.20.1 
(Edited: issue template does not allow choosing 1.20.1 as Minecraft version)

### Describe the Bug

The game crashes when loading a world that contains a powered (>= 30 RPM, i.e. fast enough to perform mixing) above a non-empty basin.

### Reproduction Steps

1. Setup a basin + mixer spinning at >= 30 RPM
2. Insert either an item or a fluid into the basin
3. Leave the world
4. Open the world

### Expected Result

The game doesn't crash

### Crash Report or Log

https://pastebin.com/jkSD4hfX

### Other Mods

Create 0.5.1.f
Farmer's Delight 1.2.3

### Mod Version

1.3.9.b

### Forge Version

47.2.0

**Comment by CarlosJohnsonW** [comment]
Same happens when running a server.

https://pastebin.com/wWxp6dr6

For some reason, when ported back to singleplayer the world does load and the mixer works fine.
