### ISSUE TITLE
Random Server Crash 0.5.1-dev

### ISSUE THREAD

**Issue by nicholasrobertm** [DragonsPlusMinecraft/CreateCentralKitchen#69]
### Minecraft Version

1.20.1

### Describe the Bug

While running the server randomly crashes and continues to crash once a chunk with some entity (not sure what) is loaded.
This was done in a modpack I'm working on. Crash report here https://pastebin.com/xd64g6xt

As a side note I was able to 'patch' this by adding the below in where the crash was happening.

```
if(blockEntity == null){
    return Blocks.AIR.defaultBlockState();
}
```
        
This was just a temporary workaround to get the world to load, I'm unsure if this is causing any unexpected behavior.

### Reproduction Steps

The exact repo steps are unknown, this happened upon exploring a world for a while on the latest version

### Expected Result

Server Doesn't crash

### Crash Report or Log

https://pastebin.com/xd64g6xt

### Other Mods

See crash report, but there are a lot of them.

### Mod Version

0.5.1

### Forge Version

47.2.0

**Comment by oliverrook** [comment]
I can confirm this exact bug. Just received it myself. I have no idea what's causing it, but there's over half a dozen completely unrelated mods mentioned, and this is the first one mentioned. It is world breaking for me, and I can no longer load the world I played on.

**Comment by MarbleGateKeeper** [comment]
Imcompatible with Computer Craft. I'll figure out a fix.

**Comment by SquidDev** [comment]
I feel a better fix here would be to fix `DelegatingSmartTileEntity` to return a sensible default value for `getBlockState`, rather than adding mixins to mods that call `getBlockEntity` within `AttachCapabilitiesEvent`.
