### ISSUE TITLE
Deployer using knife with the eternal stella from Forbidden and Arcanus mod

### ISSUE THREAD

**Issue by Limbollx** [DragonsPlusMinecraft/CreateCentralKitchen#71]
### Minecraft Version

1.20.1

### Describe the Bug

Hello, In forbidden and arcanus you have an item that when applied to a tool / armor / anything with a durability makes it unbreakable but when I place a knife that should be unbreakable in the deployer it breaks after one use.

### Reproduction Steps

1. Take a knife
2. Use a smithing template and an eternal stella in a smithing table (both of these items are added by the mod Forbidden and Arcanus)
3. Place the knife in a deployer
4. Use the deployer on a cabbage or anything

### Expected Result

It shouldn't use any durability and be able to use the knife forever

### Other Mods

https://legacy.curseforge.com/minecraft/mc-mods/forbidden-arcanus

### Mod Version

 1.3.9.d

### Forge Version

47.2.17

**Comment by MarbleGateKeeper** [comment]
After investigation I believe you should report it to Farmer's Delight.
In [here](https://github.com/vectorwing/FarmersDelight/blob/bfd4819ca9f9bc1d579d2963cfe941517de1a220/src/main/java/vectorwing/farmersdelight/common/block/entity/CuttingBoardBlockEntity.java#L90), it doesn't consider the situation that a tool is unbreakable.
