### ISSUE TITLE
World Generation Server Crash

### ISSUE THREAD

**Issue by dylanjkl** [DragonsPlusMinecraft/CreateCentralKitchen#75]
### Minecraft Version

1.20.1

### Describe the Bug

When world generating with Chunky an issue occurs that causes the server to instantly close/crash. The crash-log seems to point towards this mod, however I am unsure.

### Reproduction Steps

1. Use Chunky for World Generation
2. Server will crash unexpectedly generating a new chunk

### Expected Result

World Generation continues as normal.

### Screenshots and Videos

N/A

### Crash Report or Log

https://gist.github.com/dylanjkl/b3f38e2e7693ea2d3f0300f26dfe77c5

### Other Mods

https://gist.github.com/dylanjkl/fd3ea749082a9878ef238dfdb27205f8

### Mod Version

1.3.9.d

### Forge Version

1.20.1-forge-47.1.96

**Comment by xiaoyang5202480** [comment]
我也是，希望早日修复

**Comment by MarbleGateKeeper** [comment]
Imcompatible with Computer Craft. I'll figure out a fix.

**Comment by MarbleGateKeeper** [comment]
Duplicate of #69
