### ISSUE TITLE
Environmental: Truffle Pie missing texture

### ISSUE THREAD

**Issue by Eggmanplant** [DragonsPlusMinecraft/CreateCentralKitchen#84]
### Minecraft Version

1.19.2

### Describe the Bug

The mod tries to re-add the truffle pie in the environmental namespace, its apperaring as an missing texture block.

### Reproduction Steps

1. Download the mod and Abnormals Environmental
2. Search "Truffle" in the inventory
3. See the result
...

### Expected Result

The Truffle pie has an texture

### Screenshots and Videos

![Screenshot from 2024-03-23 07-45-54](https://github.com/DragonsPlusMinecraft/CreateCentralKitchen/assets/126160675/ed283d2b-bb52-416e-824f-d9ca9c005b96)

### Other Mods

All abnormals mods, Supplementaries, Supp. Squared

### Mod Version

1.3.10

### Forge Version

43.3.0

**Comment by Eggmanplant** [comment]
Texture pack that fixes it:
[Truffle Fix.zip](https://github.com/DragonsPlusMinecraft/CreateCentralKitchen/files/14730753/Truffle.Fix.zip)

**Comment by MarbleGateKeeper** [comment]
![image](https://github.com/DragonsPlusMinecraft/CreateCentralKitchen/assets/19358421/7bb198da-614c-416e-b255-2c0221f2d550)
Can't reproduce this problem

**Comment by Eggmanplant** [comment]
Its probably fixed

**Comment by Eggmanplant** [comment]
Still not fixed
