### ISSUE TITLE
Deployer and pot

### ISSUE THREAD

**Issue by albertosaurio65** [DragonsPlusMinecraft/CreateCentralKitchen#9]
### Minecraft Version

1.19.2

### Describe the Bug

Deployer problem:

The arm does not put ingredients in the pot or on the grill

Whatever you put, never introduce the ingredients, even when the recipe is selected on the burner, Take out yes, take out everything inside

Manually Yes I can introduce the food and put meat on the grill

I have tried using funnels to introduce but it doesn't work either

Pot problem:

The tomato sauce, for example, as it requires the tomatoes in different slots, does not work, it would have to be placed in different autos or modified so that it works only in a slot

If is necesary, i can record a video

### Reproduction Steps

1.place output in the pot and input of the basket
2.put ingredients in the basket
3.nothing occurs

1.put the basket input and the burner output with nothing on it
2.put meat in the basket
3.nothing occurs

### Expected Result

That the ingredients were put in automatically

Let the tomato sauce be made

### Screenshots and Videos

![image](https://user-images.githubusercontent.com/70109413/218283459-035edaa2-001f-48b4-8309-ca0d01051d7e.png)
![image](https://user-images.githubusercontent.com/70109413/218283465-3c2086dd-3380-4b93-99e6-cb29f9a147f2.png)
![image](https://user-images.githubusercontent.com/70109413/218283526-862ac539-3cbd-45e4-9da7-11d5dae998e2.png)
![2023-02-11_23 20 34](https://user-images.githubusercontent.com/70109413/218283538-2a81b682-9485-4c6f-8233-164074d70c0f.png)
![image](https://user-images.githubusercontent.com/70109413/218283541-bcdc1ee7-c255-4772-ae69-8896158a3f9d.png)
![image](https://user-images.githubusercontent.com/70109413/218283549-4e82583b-3453-47c7-9a65-20a4d548feb9.png)

### Other Mods

Create 0.5i

### Mod Version

create_central_kitchen-1.19.2-for-create-0.5.0.i-1.1.0

### Forge Version

Forge 43.2.4

**Comment by RaymondBlaze** [comment]
1. **(Invalid)** Mechanical Arm (and Deployer, whose support is not actually provided by us, I guess you're just using the wrong name) can put ingredients to Blaze Stove or FD's Stove.
2. **(Enhancement)** The Tomato Sauce is real problem, these kind of recipe with same ingredients won't work well if there's only 1 slot of items to input, as the Mechanical Arm's logic is to extract all items in 1 slot and try inserting them elsewhere. I will be looking into this, though currently I can't really come up with an applicable strategy that won't affect other use cases. For now, use the mixing recipes provided by FD or Central Kitchen for the Tomato Sauce. 
3.  **(Invalid)** The Cabage Roll automation you're trying to achieve actually did one thing wrong: the Mechanical Arm checks the exact item in the slot, not the ingredient the recipe needed. The reason for this kind of design is simple: though different items could all be used as ingredients, they simply don't stack in one slot. All you need to do is to change your Cooking Guide's config to not using Pork but Salmon instead.

I'll leave this open as 2 is not resolved. As for the misleading wording (deployer, grill, burner), I suggest you changing them for others to understand this issue better. Please let me know if I'm misunderstanding about those words.
