### ISSUE TITLE
Crashes while trying to make world

### ISSUE THREAD

**Issue by QianFuv** [DragonsPlusMinecraft/CreateCentralKitchen#92]
### Minecraft Version

1.20.1

### Describe the Bug

https://github.com/Creators-of-Create/Create/issues/6567
https://mclo.gs/b0fRRYJ

After removing Create Central Kitchen, can create the world normally.

**Comment by ArizTheGamer** [comment]
apparently, it also just worked after i removed a mod called smidgeon o' bliss, which is just a thingpack mod requiring json things. I thought that was the issue? 

maybe these 2 mods are conflicting in recipes?

**Comment by QianFuv** [comment]
I also have this mod. Maybe you should give some feedback over there too?
